name: aseprite

on:
    workflow_dispatch:
      inputs:
        version:
          description: "Exact Aseprite tag to build, e.g. v1.3.15. Leave empty for latest tag."
          required: false

permissions:
    contents: read

concurrency:
    group: aseprite-build
    cancel-in-progress: false

jobs:
    build:
      runs-on: windows-2022
      timeout-minutes: 120

      steps:
        - name: Checkout
          uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

        - name: Build
          id: build
          shell: cmd
          run: call build.cmd
          env:
            ASEPRITE_VERSION: ${{ github.event.inputs.version }}

        - name: Archive
          uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
          with:
            name: aseprite-${{ steps.build.outputs.ASEPRITE_VERSION }}
            path: github
            if-no-files-found: error
            retention-days: 7
